[2024-01-17 00:44:47,674] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_redshift.verificar_accesos manual__2024-01-17T00:44:35.216651+00:00 [queued]>
[2024-01-17 00:44:48,656] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_redshift.verificar_accesos manual__2024-01-17T00:44:35.216651+00:00 [queued]>
[2024-01-17 00:44:48,842] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-01-17 00:44:48,982] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2024-01-17 00:44:48,983] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-01-17 00:44:50,028] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): verificar_accesos> on 2024-01-17 00:44:35.216651+00:00
[2024-01-17 00:44:50,280] {standard_task_runner.py:52} INFO - Started process 6529 to run task
[2024-01-17 00:44:50,499] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_redshift', 'verificar_accesos', 'manual__2024-01-17T00:44:35.216651+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/ETLSachetto.py', '--cfg-path', '/tmp/tmpjwv40jf3', '--error-file', '/tmp/tmp2odf9gk5']
[2024-01-17 00:44:50,787] {standard_task_runner.py:80} INFO - Job 170: Subtask verificar_accesos
[2024-01-17 00:46:11,375] {task_command.py:371} INFO - Running <TaskInstance: dag_redshift.verificar_accesos manual__2024-01-17T00:44:35.216651+00:00 [running]> on host 8278623e2516
[2024-01-17 00:46:30,099] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=NachoSachetto
AIRFLOW_CTX_DAG_ID=dag_redshift
AIRFLOW_CTX_TASK_ID=verificar_accesos
AIRFLOW_CTX_EXECUTION_DATE=2024-01-17T00:44:35.216651+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-17T00:44:35.216651+00:00
[2024-01-17 00:47:01,570] {logging_mixin.py:115} INFO - Validaci√≥n Correcto
[2024-01-17 00:47:01,572] {python.py:173} INFO - Done. Returned value was: None
[2024-01-17 00:47:02,143] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=dag_redshift, task_id=verificar_accesos, execution_date=20240117T004435, start_date=20240117T004447, end_date=20240117T004702
[2024-01-17 00:47:04,987] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-01-17 00:47:07,242] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
